### ISSUE TITLE
Uncaught Error: useSession must be wrapped in a <SessionProvider /> 

### ISSUE THREAD

**Issue by rsmanik** [sabuhiteymurov/expo-base#52]
I tried installing the boilerplate but got the following error, no modifications has been made yet -- 

Uncaught Error: useSession must be wrapped in a <SessionProvider /> 

    at useSession (ctx.tsx:20:3)
    at AppLayout (_layout.tsx:6:29)
    at renderWithHooks (react-dom.development.js:16307:7)
    at mountIndeterminateComponent (react-dom.development.js:20076:5)
    at beginWork (react-dom.development.js:21590:10)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4166:9)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4216:16)
    at invokeGuardedCallback (react-dom.development.js:4279:1)
    at beginWork$1 (react-dom.development.js:27453:29)
    at performUnitOfWork (react-dom.development.js:26559:10)
    at workLoopSync (react-dom.development.js:26468:1)
    at renderRootSync (react-dom.development.js:26436:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25741:37)
    at workLoop (scheduler.development.js:269:18)
    at flushWork (scheduler.development.js:241:13)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:535:11)
useSession @ ctx.tsx:20
AppLayout @ _layout.tsx:6
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
callCallback @ react-dom.development.js:4166
invokeGuardedCallbackDev @ react-dom.development.js:4216
invokeGuardedCallback @ react-dom.development.js:4279
beginWork$1 @ react-dom.development.js:27453
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535

Please can you advise.

**Comment by sabuhiteymurov** [comment]
Can you include your environment? I'm unable to reproduce this error
